### ISSUE TITLE
Unexpected token T in JSON

### ISSUE THREAD

**Issue by pmow** [Starbix/dockerimages#6] opened 2018-12-15 19:23 UTC
I'm using the docker.

Pulled token according to docs.  I've reread the Token, and am using the UID/GID like my other containers.  I don't see in docs how to set MachineID or MachineName, so I grabbed the one from Preferences.xml in PMS and used the server's plex name.  Everything else is standard except I've turned on debug for the following output:

> Updating permissions...
> Updating permissions in /opt/LDAP-for-Plex...
> Updating permissions in /etc/s6.d...
> Done updating permissions.
> 
> > ldap-for-plex@0.2.0 start /opt/LDAP-for-Plex
> > node LDAPPlex.js
> 
> module.js:675
>     throw err;
>     ^
> 
> SyntaxError: /opt/LDAP-for-Plex/config/options.json: Unexpected token T in JSON at position 12
>     at JSON.parse (<anonymous>)
>     at Object.Module._extensions..json (module.js:672:27)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/opt/LDAP-for-Plex/LDAPPlex.js:35:14)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ldap-for-plex@0.2.0 start: `node LDAPPlex.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ldap-for-plex@0.2.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I was also able to get into the container using "docker exec -it LDAP-for-Plex /bin/sh" which lead me to /opt/LDAP-for-Plex/config/options.json - this file seems to be fine, it has all the settings.

Any idea?

**Comment by Starbix** [comment] 2018-12-16 11:14
I just tried it with my settings and it worked and I also updated the docs for how to find the machine id. Could you send your options.json? (without the real token)

**Comment by pmow** [comment] 2018-12-18 14:01
I've looked at the docker and original project but don't see an update to docs.  Would you mind pointing me at it?  I'm probably needing coffee.

> /opt/LDAP-for-Plex/config # cat options.json
> {
>         "debug": TRUE,
>         "port": 2389,
>         "host": "0.0.0.0",
>         "rootDN": "ou=users, o=plex.tv",
>         "plexToken": "[removed]",
>         "plexMachineID": "ba28a71e-74a2-4957-b36c-59960c3bb1c9",
>         "plexServerName": "RanchoGrande"
> }

**Comment by Starbix** [comment] 2018-12-26 12:04
Sorry for not answering your issue earlier. I think the problem is that in your config it's `TRUE` and it's not in lower case. Try `true` or `false`

**Comment by pmow** [comment] 2018-12-31 01:34
That's okay, we get a pass for the holidays 🥇 

I've made that change, and while it's running now, I don't see any debug output.  Should the logs be more verbose?  I don't see anything in /var/log so I'm at a loss.

I have also run a couple utils like LDAPExplorer and `ldapsearch -p 2389 -h 0.0.0.0 -x` but getting the following (and no debug or log output):

```
# extended LDIF
#
# LDAPv3
# base <> (default) with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# search result
search: 2
result: 32 No such object
text: No tree found for:

# numResponses: 1
```
(Specifying LDAP v2 doesn't change the result.)

**Comment by Starbix** [comment] 2018-12-31 13:22
You can find logs using `docker logs plex-ldap`.

Concerning the second question: You should probably open an issue [here](https://github.com/hjone72/LDAP-for-Plex) as I only make the Docker-part.

Can I close this issue?

**Comment by pmow** [comment] 2018-12-31 14:35
Yes, I see the logs, just didn't include them because they wouldn't differ from anyone else's.

My issue is that despite debug=true now, I get no debug logs.  It looks like the image is now including this in options.json, so I think the issue can be closed and I'll take it up at [plex-ldap](https://github.com/hjone72/LDAP-for-Plex) like you suggest.  Thanks for the insight on the case sensitivity!

**Closed as completed** 2018-12-31 14:36 UTC
